// gowww-angular/src/app/pages/Dashboard/dashboard.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  user = {
    name: 'Antony'
  }
  standings = [
    {
      id: 0,
      name: 'Premier League',
    },
    {
      id: 1,
      name: 'UEFA Champions League',
    },
  ]
  selectedStandings = 0
}

<div class="dashboard">
  <navbar></navbar>

  <main>
    <header>
      <img src="../../../assets/united.svg" alt="Manchester United" />

      <div class="header-content">
        <p>
          <span>Vamos começar?</span><span>🔥</span>
        </p>

        <h1>Bem vindo de volta, {{ user.name }}!</h1>

        <span>Sua área já está pronta com as informações do seu clube favorito</span>
      </div>
    </header>

    <div class="board-container">
      <board title="Últimos jogos" emoji="⚽" boardTitle="Manchester United"></board>
      <board title="Classificação" emoji="🏆" [boardTitle]="standings[selectedStandings].name"></board>
    </div>
  </main>
</div>

// gowww-react/src/pages/Dashboard/index.tsx
import React, { useCallback, useState } from 'react';

import Navbar from '../../components/Navbar';
import Emoji from '../../components/Emoji';
import Board from '../../components/Board';

import { Container, Wrapper, Header, HeaderContent, BoardContainer } from './styles';

import clubBrand from '../../assets/united.svg';

const Dashboard: React.FC = () => {
  const [user, setUser] = useState({
    id: Math.random(),
    name: 'Antony',
  });

  const [standings, setStandings] = useState([
    {
      id: 0,
      name: 'Premier League',
    },
    {
      id: 1,
      name: 'UEFA Champions League',
    },
  ]);

  const [selectStandings, setSelectStandings] = useState(0);

  const handleStandings = useCallback(() => {
    if (selectStandings === 0) {
      setSelectStandings(1);
    } else {
      setSelectStandings(0);
    }
  }, [selectStandings]);

  return (
    <Container>
      <Navbar />

      <Wrapper>
        <Header>
          <img src={clubBrand} alt="Manchester United"/>

          <HeaderContent>
            <p>
              <span>Vamos começar?</span><Emoji symbol="🔥" label="fire"/>
            </p>

            <h1>Bem vindo de volta, {user.name}!</h1>

            <span>Sua área já está pronta com as informações do seu clube favorito</span>
          </HeaderContent>
        </Header>

        <BoardContainer>
          <Board
            title="Últimos jogos"
            emoji="⚽"
            emojiLabel="bola de futebol"
            boardTitle="Manchester United"
          />

          <Board
            title="Classificação"
            emoji="🏆"
            emojiLabel="troféu"
            boardTitle={standings[selectStandings].name}
            handleStandings={handleStandings}
          />
        </BoardContainer>
      </Wrapper>
    </Container>
  );
};

export default Dashboard;
