// gowww-angular/src/app/pages/SignIn/signin.component.ts
import { Component } from '@angular/core';
import { NgModel } from '@angular/forms';

@Component({
  selector: 'signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css']
})
export class SignInComponent {
  user = {
    name: '',
    email: ''
  }

  onSubmit() {
    console.log(this.user)
  }
}

<div class="signin">
  <img src="../../../assets/logo.png" alt="Gowww" />

  <form #signInForm="ngForm" (ngSubmit)="signInForm.form.valid && onSubmit()">
    <div>
      <i data-feather="user"></i>

      <input #name="ngModel" [(ngModel)]="user.name" name="name" type="text" placeholder="Nome" required>
    </div>
    <div>
      <i data-feather="mail"></i>

      <input #email="ngModel" [(ngModel)]="user.email" name="email" type="text" placeholder="E-mail" required>
    </div>

    <button type="submit">Entrar</button>
  </form>
</div>

// gowww-react/src/pages/SignIn/index.tsx
import React, { useCallback, useState } from 'react';
import { FiUser } from 'react-icons/fi';

import Input from '../../components/Input';
import Button from '../../components/Button';

import { Container, Form } from './styles';

import logo from '../../assets/logo.png';

const SignIn: React.FC = () => {
  const [name, setName] = useState('');

  const handleChange= useCallback(e => {
    setName(e.target.value);
  }, []);

  const handleSubmit = useCallback(e => {
    console.log(name);

    e.preventDefault();
  }, [name]);

  return (
    <Container>
      <img src={logo} alt="Gowww"/>

      <Form onSubmit={handleSubmit}>
        <Input icon={FiUser} placeholder="Primeiro nome" value={name} onChange={handleChange} />

        <Button type="submit">Entrar</Button>
      </Form>
    </Container>
  );
};

export default SignIn;
